---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: global-hub-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/redhat-user-workloads/acm-multicluster-glo-tenant/multicluster-global-hub-agent-globalhub-1-5
      source: registry.redhat.io/multicluster-globalhub/multicluster-globalhub-agent-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/acm-multicluster-glo-tenant/multicluster-global-hub-manager-globalhub-1-5
      source: registry.redhat.io/multicluster-globalhub/multicluster-globalhub-manager-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/acm-multicluster-glo-tenant/multicluster-global-hub-operator-globalhub-1-5
      source: registry.redhat.io/multicluster-globalhub/multicluster-globalhub-rhel9-operator
    - mirrors:
        - quay.io/redhat-user-workloads/acm-multicluster-glo-tenant/glo-grafana-globalhub-1-5
      source: registry.redhat.io/multicluster-globalhub/multicluster-globalhub-grafana-rhel9
    - mirrors:
        - quay.io/redhat-user-workloads/acm-multicluster-glo-tenant/postgres-exporter-globalhub-1-5
      source: registry.redhat.io/multicluster-globalhub/multicluster-globalhub-postgres-exporter-rhel9
