name: Label PRs by User

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            lgtm
            approved
      - name: test
        run: |
          echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo "Triggering actor: ${{ github.actor }}"
